on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1-6" # 16:00 JST

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install and cache libraries
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          cache-version: 1
          packages: |
            tidyverse
            magrittr
            jsonlite
      
      - name: Update and generate the file
        run: |
          source("update_data.R")
        shell: Rscript {0}
      